#define X_START_POSITION 1

/**
 * Sprites ID
*/
#define PLAYER_SPRITE_ID 1
#define BLOCK_SPRITE_ID 2
#define EMITTER_SPRITE_ID 2
#define GATE_SPRITE_ID 3
#define BUTTON_SPRITE_ID 4
#define ACID_SPRITE_ID 4
#define ENERGY_BARRIER_SPRITE_ID 4
#define PORTAL_BLUE_SPRITE_ID 6
#define PORTAL_ORANGE_SPRITE_ID 7
#define POWERBALL_SPRITE_ID 8
#define ROCK_SPRITE_ID 8
#define TARGET_SPRITE_ID 9
#define CAKE_SPRITE_ID 10

/**
 * Objects ID
*/
#define SET_ID_CODE 0
#define PLAYER_CODE 1
#define BLOCK_CODE 2
#define GATE_CODE 3
#define BUTTON_CODE 4
#define ACID_CODE 5
#define PORTAL_CODE 6
#define POWERBALL_CODE 7
#define ROCK_CODE 8
#define ENERGY_BARRIER_CODE 9
#define EMITTER_CODE 10
#define CAKE_CODE 11

/**
 * Files 
 **/
#define BACKGROUND_FILENAME "resources/img/Fondo.png"
#define BLOCK_FILENAME "resources/img/Blocks.png"
#define EMITTER_FILENAME "resources/img/Blocks.png"
#define ICON_FILENAME "resources/img/icon.png"
#define PLAYER_FILENAME "resources/img/Patricia_Wagon_Zero_Suit.png"
#define GATE_FILENAME "resources/img/gates.png"
#define TARGET_FILENAME "resources/img/target.png"
#define ACID_FILENAME "resources/img/acidos.png"
#define BUTTON_FILENAME "resources/img/acidos.png"
#define PORTAL_BLUE_FILENAME "resources/img/portalAzul.png"
#define PORTAL_ORANGE_FILENAME "resources/img/portalNaranja.png"
#define POWERBALL_FILENAME "resources/img/liquids_powers_energy.png"
#define ROCK_FILENAME "resources/img/liquids_powers_energy.png"
#define CAKE_FILENAME "resources/img/Cake_2.png"
#define ENERGY_BARRIER_FILENAME "resources/img/acidos.png"

/**
 * PLAYER
*/
/* Idle */
#define Y_POSITION_PLAYER_IDLE 2755
#define WIDTH_PLAYER_IDLE 150
#define HEIGHT_PLAYER_IDLE 200

/* Stop */
#define Y_POSITION_PLAYER_STOP 3671
#define WIDTH_PLAYER_STOP 165
#define HEIGHT_PLAYER_STOP 214
#define MAX_WIDTH_PLAYER_STOP (10 * WIDTH_PLAYER_RESTING_IDLE + 10)

/* Rise */
#define Y_POSITION_PLAYER_RISING 855
#define WIDTH_PLAYER_RISING 143
#define HEIGHT_PLAYER_RISING 228
#define MAX_WIDTH_PLAYER_RISING (4 * WIDTH_PLAYER_RISING + 4)

/* falling */
#define Y_POSITION_PLAYER_FALLING 1835
#define WIDTH_PLAYER_FALLING 156
#define HEIGHT_PLAYER_FALLING 217
#define MAX_WIDTH_PLAYER_FALLING (4 * WIDTH_PLAYER_FALLING + 4)

/* Resting Idle */
#define Y_POSITION_PLAYER_RESTING_IDLE 2075
#define WIDTH_PLAYER_RESTING_IDLE 104
#define HEIGHT_PLAYER_RESTING_IDLE 213
#define MAX_WIDTH_RESTING_IDLE (7 * WIDTH_PLAYER_RESTING_IDLE + 7)

/* Running */
#define Y_POSITION_PLAYER_RUNNING 4123
#define WIDTH_PLAYER_RUNNING 194
#define HEIGHT_PLAYER_RUNNING 204
#define MAX_WIDTH_PLAYER_RUNNING (8 * WIDTH_PLAYER_RUNNING + 8)

/* RunningShoot */
#define Y_POSITION_PLAYER_RUNNING_SHOOT 4553
#define WIDTH_PLAYER_RUNNING_SHOOT 194
#define HEIGHT_PLAYER_RUNNING_SHOOT 208
#define MAX_WIDTH_PLAYER_RUNNING_SHOOT (8 * WIDTH_PLAYER_RUNNING_SHOOT + 8)

/* Dying */
#define Y_POSITION_PLAYER_DYING 8825
#define WIDTH_PLAYER_DYING 175
#define HEIGHT_PLAYER_DYING 260
#define MAX_WIDTH_PLAYER_DYING (9 * WIDTH_PLAYER_DYING + 9)

/* Dancing */
#define Y_POSITION_PLAYER_DANCING 6610
#define WIDTH_PLAYER_DANCING 168
#define HEIGHT_PLAYER_DANCING 242
#define MAX_WIDTH_PLAYER_DANCING (9 * WIDTH_PLAYER_DANCING + 9)

/* Fire */
#define Y_POSITION_PLAYER_FIRE 8825
#define WIDTH_PLAYER_FIRE 175
#define HEIGHT_PLAYER_FIRE 260
#define MAX_WIDTH_PLAYER_FIRE (9 * WIDTH_PLAYER_FIRE + 9)

/**
 * GATE 
 * */

/* Common */
#define WIDTH_GATE 193
#define HEIGHT_GATE 385

/* Closed */
#define Y_POSITION_GATE_CLOSED_1 2050
#define Y_POSITION_GATE_CLOSED_2 2842
#define Y_POSITION_GATE_CLOSED_3 3635
#define Y_POSITION_GATE_CLOSED_4 4428
#define Y_POSITION_GATE_CLOSED_5 5220
#define Y_POSITION_GATE_CLOSED 5255

/* Closing */
#define Y_POSITION_GATE_CLOSING_1 2050
#define Y_POSITION_GATE_CLOSING_2 2842
#define Y_POSITION_GATE_CLOSING_3 3635
#define Y_POSITION_GATE_CLOSING_4 4428
#define Y_POSITION_GATE_CLOSING_5 5220

/* Open */
#define X_POSITION_GATE_OPEN 1553
#define Y_POSITION_GATE_OPEN_1 2437
#define Y_POSITION_GATE_OPEN_2 3228
#define Y_POSITION_GATE_OPEN_3 4021
#define Y_POSITION_GATE_OPEN_4 4814
#define Y_POSITION_GATE_OPEN_5 5606

/* Opening */
#define Y_POSITION_GATE_OPENING_1 20502
#define Y_POSITION_GATE_OPENING_2 2842
#define Y_POSITION_GATE_OPENING_3 3635
#define Y_POSITION_GATE_OPENING_4 4428
#define Y_POSITION_GATE_OPENING_5 5220
#define Y_POSITION_GATE_OPENING 2050

/**
 *  ACID 
 **/

/* IDLE */
#define Y_POSITION_ACID_IDLE 1545
#define WIDTH_ACID_IDLE 300
#define HEIGHT_ACID_IDLE 61

/* TOUCHED */
#define Y_POSITION_ACID_TOUCHED 1405
#define WIDTH_ACID_TOUCHED 305
#define HEIGHT_ACID_TOUCHED 115
#define MAX_WIDTH_ACID_TOUCHED (5 * WIDTH_ACID_TOUCHED + 5)

/* POWERBALL */

/* Flying */
#define Y_POSITION_POWERBALL_FLYING 1920
#define WIDTH_POWERBALL_FLYING 110
#define HEIGHT_POWERBALL_FLYING 57

/* Flying */
#define Y_POSITION_POWERBALL_HITTING 1725
#define WIDTH_POWERBALL_HITTING 180
#define HEIGHT_POWERBALL_HITTING 160

/* Flying */
#define Y_POSITION_POWERBALL_PAW 3120
#define WIDTH_POWERBALL_PAW 165
#define HEIGHT_POWERBALL_PAW 180

/**
 * BUTTON 
 **/

/* ON */
#define Y_POSITION_BUTTON_ON 202
#define WIDTH_BUTTON_ON 175
#define HEIGHT_BUTTON_ON 64

/* OFF */
#define Y_POSITION_BUTTON_OFF 125
#define WIDTH_BUTTON_OFF 175
#define HEIGHT_BUTTON_OFF 45

/**
 * BLOCK
 **/

/* Metal */
#define Y_POSITION_BLOCK_METAL 600
#define WIDTH_BLOCK_METAL 192
#define HEIGHT_BLOCK_METAL 192

/* Stone */
#define Y_POSITION_BLOCK_STONE 173
#define WIDTH_BLOCK_STONE 192
#define HEIGHT_BLOCK_STONE 192

/* Shoot */
#define Y_POSITION_BLOCK_SHOOT 21
#define WIDTH_BLOCK_SHOOT 129
#define HEIGHT_BLOCK_SHOOT 129

/* Launch*/
#define WIDTH_BLOCK_LAUNCH 192
#define HEIGHT_BLOCK_LAUNCH 192

/* Launch_left */
#define Y_POSITION_BLOCK_LAUNCH_LEFT 815

/* Launch_right */
#define Y_POSITION_BLOCK_LAUNCH_RIGHT 1028

/* Launch_Down */
#define Y_POSITION_BLOCK_LAUNCH_DOWN 1456

/* Launch_up */
#define Y_POSITION_BLOCK_LAUNCH_UP 1242

/*Portal azul*/
#define Y_POSITION_PORTAL 1542
#define WIDTH_PORTAL 300
#define HEIGHT_PORTAL 110

/*Rock*/
#define Y_POSITION_ROCK 4513
#define WIDTH_ROCK 85
#define HEIGHT_ROCK 83

/**
 * Energy Barrier
*/
#define Y_POSITION_ENERGY_BARRIER 1627
#define WIDTH_ENERGY_BARRIER 200
#define HEIGHT_ENERGY_BARRIER 228

/**
 * Blocks Id
*/
#define METAL_BLOCK 1
#define STONE_BLOCK 2
#define SHOOT_BLOCK 3

/**
 * EMMITERS ID
*/
#define EMITTER_UP_BLOCK 1
#define EMITTER_RIGHT_BLOCK 2
#define EMITTER_DOWN_BLOCK 3
#define EMITTER_LEFT_BLOCK 4

/**
 * Powerball ID
*/
#define POWERBALL_UP 1
#define POWERBALL_RIGHT 2
#define POWERBALL_DOWN 3
#define POWERBALL_LEFT 4

/**
 * Portals directions
 * */
#define PORTAL_HORIZONTAL 1
#define PORTAL_VERTICAL 2
#define PORTAL_45GRADES 3
#define PORTAL_135GRADES 4


/*
 * Cake
*/
#define Y_POSITION_CAKE 1
#define WIDTH_CAKE 400
#define HEIGHT_CAKE 400

/*
 * Music ID
 */

#define AMBIENT_MUSIC_ID 0
#define CHELL_STEP_FX_ID 1
#define CHELL_JUMP_FX_ID 2
#define ENERGY_BALL_FX_ID 3
#define GATE_FX_ID 4
#define PORTAL_SHOT_FX_ID 5
#define ROCK_DEAD_FX_ID 6
#define CHELL_SCREAM_ID 7

/*
 * Music Files
 */

#define AMBIENT_MUSIC "resources/Music/Ambient.mp3"
#define CHELL_STEP_FX "resources/Music/chell_step2.wav"
#define CHELL_JUMP_FX "resources/Music/Chell_jump.wav"
#define ENERGY_BALL_FX "resources/Music/energy_ball_show.wav"
#define GATE_FX "resources/Music/Gate_sound.mp3"
#define PORTAL_SHOT_FX "resources/Music/portal_sound.mp3"
#define ROCK_DEAD_FX "resources/Music/Rock_dead.mp3"
#define CHELL_SCREAM "resources/Music/scream.mp3"

/* AGREGAR BLOQUE */

// "BLOCK_CODE,<CODE TIPO>,X,Y,W,H"

/* AGREGAR PLAYER */

// "PLAYER_CODE,<ID>,X,Y,W,H,<STATE>,<DIRECTION>"

/* AGREGAR GATE */

// "GATE_CODE,<ID>,X,Y,W,H,<STATE>"

/* AGREGAR BUTTON */

// "BUTTON_CODE,<ID>,X,Y,W,H,<STATE>"

/* AGREGAR ACID */

// "ACID_CODE,X,Y,W,H"

/* AGREGAR PORTAL*/

// "PORTAL_CODE,<ID>,X,Y,W,H,<CODE>,<DIRECTION>,<STATE>"
// CODE ES EL COLOR, O PODEMOS VER DE HACER PRIMARO O SECUNDARIO ALGO ASI
// 1 AZUL
// P2 NARANJA

/* AGREGAR EMITTER*/

// "EMITTER_CODE,<ID>,X,Y,W,H,<DIRECTION>,<STATE>"
// CODE ES LA DIRECCION
// 0 ARRIBA
// 1 DERECHA
// 2 ABAJO
// 3 IZQUIERDA
// STATE
// 0 RECEPTOR
// 1 EMISOR
//#define SET_ID_CODE 0
//#define PLAYER_CODE 1
//#define BLOCK_CODE 2
//#define GATE_CODE 3
//#define BUTTON_CODE 4
//#define ACID_CODE 5
//#define PORTAL_CODE 6
//#define POWERBALL_CODE 7
//#define ROCK_CODE 8
//#define ENERGY_BARRIER_CODE 9
//#define EMITTER_CODE 10
