#ifndef TP4_MACROS_H
#define TP4_MACROS_H

#define GRAVITY -10.81
#define ZERO 0
#define MAX_LIM 1000
#define DELTA_WALLS 1
#define FRICTION 0.3
#define DENSITY 1
#define METAL_RESITUTION 0.5
#define DELTA_POSITION 0.02
#define CHELL_HIGH 1.6
#define CHELL_WIDTH 0.5
#define CHELL_JUMP_FORCE -300
#define CHELL_MOVE_FORCE 1
#define ENERGY_BALL 0.1
#define ENERGY_BALL_FORCE 10
#define DELTA_ENERGY_BALL_X 0.4
#define DELTA_ENERGY_BALL_Y 0.2

#endif
